export default function() {
    return [
      { designation: 'Online Marketing and Project Coordinator at Tech Morphosis', message: 'Richard\'s natural curiosity, enthusiasm, and willingness to go the extra mile make him an excellent problem solver - he keeps pegging away until he finds a way. Was a pleasure to work with him.', name: 'Mohit Bajaj', imgSrc: 'images/mohit_techmo.jpg' },
      { designation: 'Assistant Project Manager at Finoux Solutions', message: 'Having worked with Richard for around 9 months, he is indeed a good team player and an all-rounder. His ability and confidence to tackle situations and work under pressure are exemplary. Being an avid and inquisitive tyro his hunger for knowledge helps him achieve some avant-grande results. Punctual, focused and detail-oriented are just some of his idiosyncrasies... Wishing him all the best for this future!', name: 'Gaurang Mohite', imgSrc: 'images/gaurang_tech.jpg' },
      { designation: ' Director at Techmorphosis ', message: 'Richard is a dedicated and hard worker. Instead of taking the easy way out in any situation, Richard focusses on the best possible way to implement things and takes on the responsibility of delivering at an early stage. His skill set and mind set will make him a good leader.', name: 'Pavan Hemdev', imgSrc: 'images/pavan_tech.jpg' },
      { designation: 'Android Developer at Techmorphosis', message: 'Richard is extremely passionate about learning new technology and his skills in UX and UI development is awesome.He is responsible and takes full ownership of his work or project.He is hard-working and quick learner, tries to give his best everytime.The way he present himself and his thoughts through his awesome communication and verbal skills, he can convince you in no time.Any team or company will be lucky to have him on their side.', name: 'Gaurav Rai', imgSrc: 'images/gaurav_tech.gif' },
      { designation: 'iOS Developer at Cardinbox Technologies Pvt. Ltd', message: 'Richard is very energetic and always aware of the latest updates. He is very hard working and works with that same level of dedication throughout the day. He is very determined and focused.', name: 'Divya Dinesh', imgSrc: 'images/divya_tech.jpg' },
      { designation: 'Partnership Development Executive at Wemet Group', message: 'Richard did an excellent job in this position and was an asset to our organization during his tenure with the office. He has excellent written and verbal communication skills, is extremely organized, can work independently and is able to follow through to ensure that the job gets done.', name: 'Minal Jain', imgSrc: 'images/minal_datam.jpg' },
      { designation: 'Associate Project Manager at Lionbridge', message: 'Richard is multi-talented. His research techniques is at par and the way he presents himself in front of the audience is something worth watching. He will be a great asset to any team/company where he will be working in future. A true team player and a performer too.', name: 'Sudhir Kumbhar', imgSrc: 'images/sudhir_datam.jpg' }
    ];
  }
  